/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  EmojiPack,
} from './models/emoji-pack';

export namespace Components {
  interface CoolEmojiPicker {
    'appendToBody': boolean;
    'btnEmojiClasses': string;
    'emojiData': Array<EmojiPack>;
    'pickerMaxHeight': number;
    'pickerWidth': number;
    'recentEmojiLimit': number;
    'recentEmojiStorageName': string;
    'recentEmojisFeat': boolean;
    'skinsSelection': boolean;
    'twemojiExtension': string;
    'twemojiFolder': string;
    'twemojiPath': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLCoolEmojiPickerElement extends Components.CoolEmojiPicker, HTMLStencilElement {}
  var HTMLCoolEmojiPickerElement: {
    prototype: HTMLCoolEmojiPickerElement;
    new (): HTMLCoolEmojiPickerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'cool-emoji-picker': HTMLCoolEmojiPickerElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface CoolEmojiPicker extends JSXBase.HTMLAttributes<HTMLCoolEmojiPickerElement> {
    'appendToBody'?: boolean;
    'btnEmojiClasses'?: string;
    'emojiData'?: Array<EmojiPack>;
    'pickerMaxHeight'?: number;
    'pickerWidth'?: number;
    'recentEmojiLimit'?: number;
    'recentEmojiStorageName'?: string;
    'recentEmojisFeat'?: boolean;
    'skinsSelection'?: boolean;
    'twemojiExtension'?: string;
    'twemojiFolder'?: string;
    'twemojiPath'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'cool-emoji-picker': CoolEmojiPicker;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


